HostingProject/Controllers/PlansAdminController.cs
using HostingProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HostingProject.Controllers
{
    
    public class PlansAdminController : Controller
    {
        private ProjDbContext db;

        public PlansAdminController(ProjDbContext _db) 
        {
            db= _db;
        }
        public IActionResult Index()
        {
            return View(db.Plans);
        }

        public IActionResult AddPlan() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddPlan(PlanViewModel plan)
        {
            
            db.Plans.Add(plan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EditPlan(PlanViewModel plan)
        {
            if (plan == null)
            {
                return RedirectToAction("Index");
            }
            else 
            {
                db.Plans.Update(plan);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(plan);
        }


        [HttpGet]
        public IActionResult EditPlan(int id)
        {
            var plan = db.Plans.Find(id);
            if (plan == null)
            {
                return RedirectToAction("Index");
            }
            return View(plan);
        }

    }
}

HostingProject/Views/PlansAdmin/AddPlan.cshtml
@model HostingProject.Models.PlanViewModel

@{
    ViewData["Title"] = "AddPlan";
}



<div class="container-xl">
    <h1>AddPlan</h1>

    <h4>PlanViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12 account-form">
                    <form method="post" asp-action="AddPlan" asp-controller="PlansAdmin">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="planName" class="control-label"></label>
                            <input asp-for="planName" class="form-control" />
                            <span asp-validation-for="planName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="planType" class="control-label"></label>
                            <input asp-for="planType" class="form-control" />
                            <span asp-validation-for="planType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="serverType" class="control-label"></label>
                            <input asp-for="serverType" class="form-control" />
                            <span asp-validation-for="serverType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="storage" class="control-label"></label>
                            <input asp-for="storage" class="form-control" />
                            <span asp-validation-for="storage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="RAM" class="control-label"></label>
                            <input asp-for="RAM" class="form-control" />
                            <span asp-validation-for="RAM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="database" class="control-label"></label>
                            <input asp-for="database" class="form-control" />
                            <span asp-validation-for="database" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="bandwidth" class="control-label"></label>
                            <input asp-for="bandwidth" class="form-control" />
                            <span asp-validation-for="bandwidth" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CPU" class="control-label"></label>
                            <input asp-for="CPU" class="form-control" />
                            <span asp-validation-for="CPU" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="protection" class="control-label"></label>
                            <input asp-for="protection" class="form-control" />
                            <span asp-validation-for="protection" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="price" class="control-label"></label>
                            <input asp-for="price" class="form-control" />
                            <span asp-validation-for="protection" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="ssl" /> @Html.DisplayNameFor(model => model.ssl)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="upgrade" /> @Html.DisplayNameFor(model => model.upgrade)
                            </label>
                        </div>
                        <div class="form-group">
                            <label asp-for="CreatedDate" class="control-label"></label>
                            <input asp-for="CreatedDate" class="form-control" />
                            <span asp-validation-for="CreatedDate" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>


</div>

HostingProject/Views/PlansAdmin/EditPlan.cshtml
@model HostingProject.Models.PlanViewModel



<div class="container-fluid">

    <h1>EditPlan</h1>

    <h4>PlanViewModel</h4>
    <hr />

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12 account-form">
                    <form asp-action="EditPlan" method="post" asp-controller="PlansAdmin">
                        @Html.HiddenFor(model=> model.planId)
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="planId" class="control-label"></label>
                            <input asp-for="planId" class="form-control" />
                            <span asp-validation-for="planId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="planName" class="control-label"></label>
                            <input asp-for="planName" class="form-control" />
                            <span asp-validation-for="planName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="planType" class="control-label"></label>
                            <input asp-for="planType" class="form-control" value="@Model.planType" />
                            <span asp-validation-for="planType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="serverType" class="control-label"></label>
                            <input asp-for="serverType" class="form-control" />
                            <span asp-validation-for="serverType" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="storage" class="control-label"></label>
                            <input asp-for="storage" class="form-control" />
                            <span asp-validation-for="storage" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="RAM" class="control-label"></label>
                            <input asp-for="RAM" class="form-control" />
                            <span asp-validation-for="RAM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="database" class="control-label"></label>
                            <input asp-for="database" class="form-control" />
                            <span asp-validation-for="database" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="bandwidth" class="control-label"></label>
                            <input asp-for="bandwidth" class="form-control" />
                            <span asp-validation-for="bandwidth" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CPU" class="control-label"></label>
                            <input asp-for="CPU" class="form-control" />
                            <span asp-validation-for="CPU" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="protection" class="control-label"></label>
                            <input asp-for="protection" class="form-control" />
                            <span asp-validation-for="protection" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="ssl" /> @Html.DisplayNameFor(model => model.ssl)
                            </label>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="upgrade" /> @Html.DisplayNameFor(model => model.upgrade)
                            </label>
                        </div>
                        <div class="form-group">
                            <label asp-for="price" class="control-label"></label>
                            <input asp-for="price" class="form-control" />
                            <span asp-validation-for="price" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CreatedDate" class="control-label"></label>
                            <input asp-for="CreatedDate" class="form-control" />
                            <span asp-validation-for="CreatedDate" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
        <div class="col-md-4"></div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</div>

HostingProject/Views/PlansAdmin/Index.cshtml
@model IEnumerable<PlanViewModel>

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @if (Model.Any())
            {
                <div class="mb-3">
                    <a class="btn btn-success" asp-action="AddPlan" asp-controller="PlansAdmin">Add Plan</a>
                </div>
                
                <table class="table-bordered" style="width: 100%; text-align:center;">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(x => x.planId)</th>
                            <th>@Html.DisplayNameFor(x => x.planName)</th>
                            <th>@Html.DisplayNameFor(x => x.planType)</th>
                            <th>@Html.DisplayNameFor(x => x.price)</th>
                            <th>Functionality</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.planId</td>
                                <td>@item.planName</td>
                                <td>@item.planType</td>
                                <td>@item.price</td>
                                <td>
                                    <a asp-action="EditPlan" asp-controller="PlansAdmin" asp-route-id="@item.planId" class="btn btn-warning">Edit</a>
                                    <a asp-action="EditPlan" asp-controller="PlansAdmin" asp-route-id="@item.planId" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            }
            else
            {
                <h1>There's No plans To Display</h1>
                <a class="btn btn-success" asp-action="AddPlan" asp-controller="PlansAdmin">Add Plan</a>
            }


        </div>
        <div class="col-md-2"></div>
    </div>
</div>